export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  stock: number;
  description: string;
}

export const mockProducts: Product[] = [
  // Grains & Cereals
  {
    id: '1',
    name: 'Premium Basmati Rice',
    category: 'Grains',
    price: 85,
    stock: 150,
    description: 'Long-grain aromatic basmati rice from the Himalayan foothills',
  },
  {
    id: '2',
    name: 'Whole Wheat Flour',
    category: 'Grains',
    price: 45,
    stock: 200,
    description: 'Stone-ground whole wheat flour perfect for baking',
  },
  {
    id: '3',
    name: 'Quinoa Organic',
    category: 'Grains',
    price: 120,
    stock: 80,
    description: 'Gluten-free organic quinoa rich in protein',
  },
  {
    id: '4',
    name: 'Rolled Oats',
    category: 'Grains',
    price: 35,
    stock: 120,
    description: 'Heart-healthy rolled oats for breakfast',
  },
  {
    id: '5',
    name: 'Millet Grains',
    category: 'Grains',
    price: 40,
    stock: 95,
    description: 'Nutrient-rich ancient grain perfect for porridge',
  },
  
  // Beverages
  {
    id: '6',
    name: 'Arabica Coffee Beans',
    category: 'Beverages',
    price: 150,
    stock: 60,
    description: 'Premium arabica beans with rich chocolate notes',
  },
  {
    id: '7',
    name: 'Green Tea Premium',
    category: 'Beverages',
    price: 75,
    stock: 100,
    description: 'Organic Japanese green tea leaves',
  },
  {
    id: '8',
    name: 'Black Tea Assam',
    category: 'Beverages',
    price: 55,
    stock: 140,
    description: 'Strong and malty Assam black tea',
  },
  {
    id: '9',
    name: 'Cocoa Powder',
    category: 'Beverages',
    price: 90,
    stock: 70,
    description: 'Pure unsweetened cocoa powder for hot chocolate',
  },
  {
    id: '10',
    name: 'Orange Juice Concentrate',
    category: 'Beverages',
    price: 65,
    stock: 85,
    description: '100% pure orange juice concentrate',
  },
  
  // Oils & Fats
  {
    id: '11',
    name: 'Extra Virgin Olive Oil',
    category: 'Oils',
    price: 120,
    stock: 75,
    description: 'Cold-pressed premium olive oil from Mediterranean',
  },
  {
    id: '12',
    name: 'Coconut Oil Organic',
    category: 'Oils',
    price: 80,
    stock: 90,
    description: 'Organic cold-pressed coconut oil',
  },
  {
    id: '13',
    name: 'Sunflower Oil',
    category: 'Oils',
    price: 45,
    stock: 110,
    description: 'Light and healthy sunflower cooking oil',
  },
  {
    id: '14',
    name: 'Ghee Clarified Butter',
    category: 'Oils',
    price: 95,
    stock: 65,
    description: 'Pure clarified butter with rich nutty flavor',
  },
  {
    id: '15',
    name: 'Avocado Oil',
    category: 'Oils',
    price: 110,
    stock: 55,
    description: 'Premium cold-pressed avocado oil',
  },
  
  // Sweeteners
  {
    id: '16',
    name: 'Organic Honey',
    category: 'Sweeteners',
    price: 85,
    stock: 80,
    description: 'Pure raw honey from wildflowers',
  },
  {
    id: '17',
    name: 'Brown Sugar',
    category: 'Sweeteners',
    price: 35,
    stock: 130,
    description: 'Natural unrefined brown sugar',
  },
  {
    id: '18',
    name: 'Maple Syrup',
    category: 'Sweeteners',
    price: 125,
    stock: 45,
    description: 'Pure Canadian maple syrup grade A',
  },
  {
    id: '19',
    name: 'Stevia Natural',
    category: 'Sweeteners',
    price: 95,
    stock: 70,
    description: 'Zero-calorie natural sweetener from stevia leaves',
  },
  {
    id: '20',
    name: 'Jaggery Organic',
    category: 'Sweeteners',
    price: 40,
    stock: 100,
    description: 'Traditional organic jaggery blocks',
  },
  
  // Spices & Condiments
  {
    id: '21',
    name: 'Turmeric Powder',
    category: 'Spices',
    price: 30,
    stock: 160,
    description: 'Pure ground turmeric with anti-inflammatory properties',
  },
  {
    id: '22',
    name: 'Black Pepper Whole',
    category: 'Spices',
    price: 55,
    stock: 120,
    description: 'Aromatic whole black peppercorns',
  },
  {
    id: '23',
    name: 'Cinnamon Sticks',
    category: 'Spices',
    price: 70,
    stock: 85,
    description: 'Premium Ceylon cinnamon sticks',
  },
  {
    id: '24',
    name: 'Red Chili Powder',
    category: 'Spices',
    price: 25,
    stock: 140,
    description: 'Hot and spicy red chili powder',
  },
  {
    id: '25',
    name: 'Cumin Seeds',
    category: 'Spices',
    price: 35,
    stock: 110,
    description: 'Aromatic whole cumin seeds',
  },
  
  // Dairy & Alternatives
  {
    id: '26',
    name: 'Almond Milk',
    category: 'Dairy',
    price: 75,
    stock: 90,
    description: 'Unsweetened almond milk, dairy-free alternative',
  },
  {
    id: '27',
    name: 'Greek Yogurt',
    category: 'Dairy',
    price: 60,
    stock: 70,
    description: 'Creamy protein-rich Greek yogurt',
  },
  {
    id: '28',
    name: 'Soy Milk',
    category: 'Dairy',
    price: 50,
    stock: 95,
    description: 'Fortified soy milk with calcium',
  },
  {
    id: '29',
    name: 'Butter Unsalted',
    category: 'Dairy',
    price: 80,
    stock: 85,
    description: 'Premium unsalted butter from grass-fed cows',
  },
  {
    id: '30',
    name: 'Cheese Cheddar',
    category: 'Dairy',
    price: 140,
    stock: 60,
    description: 'Aged sharp cheddar cheese blocks',
  },
  
  // Fruits & Vegetables
  {
    id: '31',
    name: 'Dried Mango Slices',
    category: 'Fruits',
    price: 65,
    stock: 75,
    description: 'Sweet and chewy dried mango slices',
  },
  {
    id: '32',
    name: 'Mixed Berries Frozen',
    category: 'Fruits',
    price: 85,
    stock: 80,
    description: 'Mixed berries (strawberries, blueberries, raspberries)',
  },
  {
    id: '33',
    name: 'Dates Medjool',
    category: 'Fruits',
    price: 95,
    stock: 65,
    description: 'Large, sweet Medjool dates',
  },
  {
    id: '34',
    name: 'Raisins Golden',
    category: 'Fruits',
    price: 40,
    stock: 100,
    description: 'Sweet golden raisins perfect for baking',
  },
  {
    id: '35',
    name: 'Almonds Raw',
    category: 'Nuts',
    price: 110,
    stock: 85,
    description: 'Premium raw almonds with skin',
  },
  {
    id: '36',
    name: 'Cashews Raw',
    category: 'Nuts',
    price: 130,
    stock: 70,
    description: 'Creamy raw cashews perfect for snacking',
  },
  {
    id: '37',
    name: 'Walnuts Halves',
    category: 'Nuts',
    price: 115,
    stock: 60,
    description: 'Premium walnut halves rich in omega-3',
  },
  {
    id: '38',
    name: 'Peanuts Roasted',
    category: 'Nuts',
    price: 45,
    stock: 120,
    description: 'Salted roasted peanuts',
  },
  {
    id: '39',
    name: 'Pistachios Shelled',
    category: 'Nuts',
    price: 145,
    stock: 55,
    description: 'Premium shelled pistachios',
  },
  {
    id: '40',
    name: 'Mixed Nuts',
    category: 'Nuts',
    price: 105,
    stock: 75,
    description: 'Healthy mix of almonds, cashews, and walnuts',
  },
  
  // Legumes & Pulses
  {
    id: '41',
    name: 'Red Lentils',
    category: 'Legumes',
    price: 35,
    stock: 140,
    description: 'High-protein red lentils that cook quickly',
  },
  {
    id: '42',
    name: 'Chickpeas Dried',
    category: 'Legumes',
    price: 40,
    stock: 110,
    description: 'Dried chickpeas perfect for hummus and curries',
  },
  {
    id: '43',
    name: 'Black Beans',
    category: 'Legumes',
    price: 30,
    stock: 125,
    description: 'Nutritious black beans rich in fiber',
  },
  {
    id: '44',
    name: 'Green Peas Split',
    category: 'Legumes',
    price: 25,
    stock: 130,
    description: 'Split green peas for soups and dals',
  },
  {
    id: '45',
    name: 'Kidney Beans Red',
    category: 'Legumes',
    price: 35,
    stock: 105,
    description: 'Red kidney beans for chili and stews',
  },
];
